/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function specVersion(): string
export declare function canonicalJson(valueJson: string): string
export declare function contextIdentity(ctxJson: string): string
export declare function validateVerdict(verdictJson: string): string
export declare function applyTransform(targetJson: string, path: string, valueJson: string): string
export declare function combineVerdicts(verdictsJson: string): string
export declare function enforce(ctxJson: string, verdictJson: string, mode: string): string
