// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//! Cross-SDK golden vectors for §10 canonical JSON and context identity.
//!
//! `conformance/golden/identity.json` is generated by
//! `scripts/gen-golden-identity.py` from this crate; every language
//! binding runs an equivalent test against the same file. A divergence
//! here means an SDK is not calling into the Rust core.

use agent_hooks::{canonical_json, context_identity, AgentContext};
use serde_json::Value;

fn load() -> Vec<Value> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../conformance/golden/identity.json");
    let doc: Value = serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    doc["fixtures"].as_array().unwrap().clone()
}

#[test]
fn golden_canonical_json() {
    for f in load() {
        let got = canonical_json(&f["ctx"]);
        assert_eq!(
            got,
            f["expect"]["canonical_json"].as_str().unwrap(),
            "canonical_json mismatch for {}",
            f["id"]
        );
    }
}

#[test]
fn golden_context_identity() {
    for f in load() {
        let ctx: AgentContext = serde_json::from_value(f["ctx"].clone()).unwrap();
        let got = context_identity(&ctx);
        assert_eq!(
            got,
            f["expect"]["context_identity"].as_str().unwrap(),
            "context_identity mismatch for {}",
            f["id"]
        );
    }
}

#[test]
fn golden_l2_l3_stripped() {
    let fs = load();
    let g05 = fs.iter().find(|f| f["id"] == "G-05-l2-l3-stripped").unwrap();
    let g05b = fs.iter().find(|f| f["id"] == "G-05b-l2-l3-baseline").unwrap();
    assert_eq!(
        g05["expect"]["context_identity"], g05b["expect"]["context_identity"],
        "L2/L3 fields must not affect context_identity (§10.2)"
    );
}
