# Type stubs for the PyO3 native module (agent_hooks._core).
# All functions take/return UTF-8 JSON strings.

SPEC_VERSION: str

class AgentHooksCoreError(ValueError):
    """Raised by every _core function on failure. ``.code`` is the §11
    ``host_error:*`` wire string."""
    code: str

def spec_version() -> str: ...
def canonical_json(value_json: str, /) -> str: ...
def context_identity(ctx_json: str, /) -> str: ...
def validate_verdict(verdict_json: str, /) -> str: ...
def apply_transform(target_json: str, path: str, value_json: str, /) -> str: ...
def combine_verdicts(verdicts_json: str, /) -> str: ...
def enforce(ctx_json: str, verdict_json: str, mode: str, /) -> str: ...
